### ISSUE TITLE
四酸后白露级，朝潮级以及夕云级DD加成有误？

### ISSUE THREAD

**Issue by TinaFeng** [TeamFleet/KCKit#20]
呼叫舰队里这些舰四酸后显示每件装备都有属性加成。实际上应该是第一件和第二件有加成，第三件就没有了。游戏里装备第三个四酸后没有蓝字
![image](https://user-images.githubusercontent.com/9577226/230560806-ee3d39a1-b766-40fe-aba0-fa5aa21cc8c1.png)

**Comment by Diablohu** [comment]
implemented https://github.com/TeamFleet/KCKit/commit/5105a75041a87012f567db9af29de55d228fa0ad
